import { FC, useEffect, useState } from 'react';
import styled from 'styled-components';

const AnimeQuote: FC = () => {
  const [animeQuote, setAnimeQuote] = useState({
    quote:
      "I hate waiting, but if waiting means being able to be with you, I'll wait for as long as forever",
    character: 'Aisaka Taiga',
    anime: 'Toradora',
  });

  interface AnimeQuote {
    quote: string;
    character: string;
    anime: string;
  }

  useEffect(() => {
    fetch('https://animechan.vercel.app/api/random')
      .then((response) => response.json())
      .then((quote: AnimeQuote) => setAnimeQuote(quote));
  }, []);
  return (
    <AnimeQuoteWrapper>
      <p>
        <i>&quot;{animeQuote.quote}&quot;</i>
      </p>
      <p>
        {animeQuote.character}, <b>{animeQuote.anime}</b>
        {' [Generated by '}
        <a
          href="https://animechan.vercel.app/"
          target="_blank"
          rel="noreferrer"
        >
          Animechan
        </a>
        {']'}
      </p>
    </AnimeQuoteWrapper>
  );
};

export default AnimeQuote;

const AnimeQuoteWrapper = styled.div`
  margin: 0px 20px;
`;
